package com.kyanite.deeperdarker.util.datagen;

import com.kyanite.deeperdarker.DeeperDarker;
import com.kyanite.deeperdarker.compat.create.DDCreateCompat;
import com.kyanite.deeperdarker.content.*;
import com.kyanite.deeperdarker.world.otherside.OthersideBiomes;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.Util;
import net.minecraft.core.registries.BuiltInRegistries;

public class DDENLanguageProvider extends FabricLanguageProvider {
    public DDENLanguageProvider(FabricDataOutput dataOutput) {
        super(dataOutput);
    }

    @Override
    public void generateTranslations(TranslationBuilder translationBuilder) {
        translationBuilder.add("itemGroup.deeperdarker", "Deeper and Darker");
        translationBuilder.add("item.deeperdarker.smithing_template.warden_upgrade.applies_to", "Netherite Equipment");
        translationBuilder.add("item.deeperdarker.smithing_template.warden_upgrade.ingredients", "Reinforced Echo Shard");
        translationBuilder.add("item.deeperdarker.smithing_template.warden_upgrade.base_slot_description", "Add netherite armor, weapon, or tool");
        translationBuilder.add("item.deeperdarker.smithing_template.warden_upgrade.additions_slot_description", "Add Reinforced Echo Shard");
        translationBuilder.add("upgrade.deeperdarker.warden_upgrade", "Warden Upgrade");
        translationBuilder.add("item.deeperdarker.smithing_template.guardian_upgrade.applies_to", "Warden Equipment");
        translationBuilder.add("item.deeperdarker.smithing_template.guardian_upgrade.ingredients", "Soul of Virtue");
        translationBuilder.add("item.deeperdarker.smithing_template.guardian_upgrade.base_slot_description", "Add warden armor, weapon, or tool");
        translationBuilder.add("item.deeperdarker.smithing_template.guardian_upgrade.additions_slot_description", "Add Soul of Virtue");
        translationBuilder.add("upgrade.deeperdarker.guardian_upgrade", "Guardian Upgrade");
        translationBuilder.add(DDBlocks.ENRICHED_ECHO_LOG, "Enriched Echo Log");
        translationBuilder.add(DDBlocks.ECHO_LOG, "Echo Log");
        translationBuilder.add(DDBlocks.ECHO_WOOD, "Echo Wood");
        translationBuilder.add(DDBlocks.STRIPPED_ECHO_LOG, "Stripped Echo Log");
        translationBuilder.add(DDBlocks.STRIPPED_ECHO_WOOD, "Stripped Echo Wood");
        translationBuilder.add(DDBlocks.ECHO_LEAVES, "Echo Leaves");
        translationBuilder.add(DDBlocks.ECHO_PLANKS, "Echo Planks");
        translationBuilder.add(DDBlocks.ECHO_STAIRS, "Echo Stairs");
        translationBuilder.add(DDBlocks.ECHO_SLAB, "Echo Slab");
        translationBuilder.add(DDBlocks.ECHO_FENCE, "Echo Fence");
        translationBuilder.add(DDBlocks.ECHO_FENCE_GATE, "Echo Fence Gate");
        translationBuilder.add(DDBlocks.ECHO_DOOR, "Echo Door");
        translationBuilder.add(DDBlocks.ECHO_TRAPDOOR, "Echo Trapdoor");
        translationBuilder.add(DDBlocks.ECHO_PRESSURE_PLATE, "Echo Pressure Plate");
        translationBuilder.add(DDBlocks.ECHO_BUTTON, "Echo Button");
        translationBuilder.add(DDBlocks.ECHO_SIGN, "Echo Sign");
        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.BLOCK.getKey(DDBlocks.ECHO_WALL_SIGN)), "Echo Wall Sign");
        translationBuilder.add(DDBlocks.ECHO_HANGING_SIGN, "Echo Hanging Sign");
        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.BLOCK.getKey(DDBlocks.ECHO_WALL_HANGING_SIGN)), "Echo Wall Hanging Sign");
        translationBuilder.add(DDBlocks.ECHO_SAPLING, "Echo Sapling");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_LOG, "Sculk Spruce Log");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_WOOD, "Sculk Spruce Wood");
        translationBuilder.add(DDBlocks.STRIPPED_SCULK_SPRUCE_LOG, "Stripped Sculk Spruce Log");
        translationBuilder.add(DDBlocks.STRIPPED_SCULK_SPRUCE_WOOD, "Stripped Sculk Spruce Wood");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_LEAVES, "Sculk Spruce Leaves");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_PLANKS, "Sculk Spruce Planks");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_STAIRS, "Sculk Spruce Stairs");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_SLAB, "Sculk Spruce Slab");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_FENCE, "Sculk Spruce Fence");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_FENCE_GATE, "Sculk Spruce Fence Gate");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_DOOR, "Sculk Spruce Door");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_TRAPDOOR, "Sculk Spruce Trapdoor");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_PRESSURE_PLATE, "Sculk Spruce Pressure Plate");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_BUTTON, "Sculk Spruce Button");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_SIGN, "Sculk Spruce Sign");
        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.BLOCK.getKey(DDBlocks.SCULK_SPRUCE_WALL_SIGN)), "Sculk Spruce Wall Sign");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_HANGING_SIGN, "Sculk Spruce Hanging Sign");
        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.BLOCK.getKey(DDBlocks.SCULK_SPRUCE_WALL_HANGING_SIGN)), "Sculk Spruce Wall Hanging Sign");
        translationBuilder.add(DDBlocks.SCULK_SPRUCE_SAPLING, "Sculk Spruce Sapling");
        translationBuilder.add(DDBlocks.SCULK_STONE, "Sculk Stone");
        translationBuilder.add(DDBlocks.SCULK_STONE_STAIRS, "Sculk Stone Stairs");
        translationBuilder.add(DDBlocks.SCULK_STONE_SLAB, "Sculk Stone Slab");
        translationBuilder.add(DDBlocks.SCULK_STONE_WALL, "Sculk Stone Wall");
        translationBuilder.add(DDBlocks.COBBLED_SCULK_STONE, "Cobbled Sculk Stone");
        translationBuilder.add(DDBlocks.COBBLED_SCULK_STONE_STAIRS, "Cobbled Sculk Stone Stairs");
        translationBuilder.add(DDBlocks.COBBLED_SCULK_STONE_SLAB, "Cobbled Sculk Stone Slab");
        translationBuilder.add(DDBlocks.COBBLED_SCULK_STONE_WALL, "Cobbled Sculk Stone Wall");
        translationBuilder.add(DDBlocks.POLISHED_SCULK_STONE, "Polished Sculk Stone");
        translationBuilder.add(DDBlocks.POLISHED_SCULK_STONE_STAIRS, "Polished Sculk Stone Stairs");
        translationBuilder.add(DDBlocks.POLISHED_SCULK_STONE_SLAB, "Polished Sculk Stone Slab");
        translationBuilder.add(DDBlocks.POLISHED_SCULK_STONE_WALL, "Polished Sculk Stone Wall");
        translationBuilder.add(DDBlocks.SCULK_STONE_BRICKS, "Sculk Stone Bricks");
        translationBuilder.add(DDBlocks.SCULK_STONE_BRICK_STAIRS, "Sculk Stone Brick Stairs");
        translationBuilder.add(DDBlocks.SCULK_STONE_BRICK_SLAB, "Sculk Stone Brick Slab");
        translationBuilder.add(DDBlocks.SCULK_STONE_BRICK_WALL, "Sculk Stone Brick Wall");
        translationBuilder.add(DDBlocks.SCULK_STONE_TILES, "Sculk Stone Tiles");
        translationBuilder.add(DDBlocks.SCULK_STONE_TILE_STAIRS, "Sculk Stone Tile Stairs");
        translationBuilder.add(DDBlocks.SCULK_STONE_TILE_SLAB, "Sculk Stone Tile Slab");
        translationBuilder.add(DDBlocks.SCULK_STONE_TILE_WALL, "Sculk Stone Tile Wall");
        translationBuilder.add(DDBlocks.SMOOTH_SCULK_STONE, "Smooth Sculk Stone");
        translationBuilder.add(DDBlocks.SMOOTH_SCULK_STONE_STAIRS, "Smooth Sculk Stone Stairs");
        translationBuilder.add(DDBlocks.SMOOTH_SCULK_STONE_SLAB, "Smooth Sculk Stone Slab");
        translationBuilder.add(DDBlocks.SMOOTH_SCULK_STONE_WALL, "Smooth Sculk Stone Wall");
        translationBuilder.add(DDBlocks.CUT_SCULK_STONE, "Cut Sculk Stone");
        translationBuilder.add(DDBlocks.CUT_SCULK_STONE_STAIRS, "Cut Sculk Stone Stairs");
        translationBuilder.add(DDBlocks.CUT_SCULK_STONE_SLAB, "Cut Sculk Stone Slab");
        translationBuilder.add(DDBlocks.CUT_SCULK_STONE_WALL, "Cut Sculk Stone Wall");
        translationBuilder.add(DDBlocks.CHISELED_SCULK_STONE, "Chiseled Sculk Stone");
        translationBuilder.add(DDBlocks.SCULK_GRIME, "Sculk Grime");
        translationBuilder.add(DDBlocks.SCULK_GRIME_BRICKS, "Sculk Grime Bricks");
        translationBuilder.add(DDBlocks.SCULK_GRIME_BRICK_STAIRS, "Sculk Grime Brick Stairs");
        translationBuilder.add(DDBlocks.SCULK_GRIME_BRICK_SLAB, "Sculk Grime Brick Slab");
        translationBuilder.add(DDBlocks.SCULK_GRIME_BRICK_WALL, "Sculk Grime Brick Wall");
        translationBuilder.add(DDBlocks.FRAGILE_SCULK_GRIME_BRICKS, "Fragile Sculk Grime Bricks");
        translationBuilder.add(DDBlocks.SCULK_GRIME_LOCK, "Sculk Grime Lock");
        translationBuilder.add(DDBlocks.PROTECTED_SCULK_GRIME_GLASS, "Protected Sculk Grime Glass");
        translationBuilder.add(DDBlocks.SCULK_GRIME_GLASS, "Sculk Grime Glass");
        translationBuilder.add(DDBlocks.SCULK_GRIME_GLASS_PANE, "Sculk Grime Glass Pane");
        translationBuilder.add(DDBlocks.RETURN_STATUE, "Return Statue");
        translationBuilder.add(DDBlocks.GLOOMSLATE, "Gloomslate");
        translationBuilder.add(DDBlocks.GLOOMSLATE_STAIRS, "Gloomslate Stairs");
        translationBuilder.add(DDBlocks.GLOOMSLATE_SLAB, "Gloomslate Slab");
        translationBuilder.add(DDBlocks.GLOOMSLATE_WALL, "Gloomslate Wall");
        translationBuilder.add(DDBlocks.COBBLED_GLOOMSLATE, "Cobbled Gloomslate");
        translationBuilder.add(DDBlocks.COBBLED_GLOOMSLATE_STAIRS, "Cobbled Gloomslate Stairs");
        translationBuilder.add(DDBlocks.COBBLED_GLOOMSLATE_SLAB, "Cobbled Gloomslate Slab");
        translationBuilder.add(DDBlocks.COBBLED_GLOOMSLATE_WALL, "Cobbled Gloomslate Wall");
        translationBuilder.add(DDBlocks.POLISHED_GLOOMSLATE, "Polished Gloomslate");
        translationBuilder.add(DDBlocks.POLISHED_GLOOMSLATE_STAIRS, "Polished Gloomslate Stairs");
        translationBuilder.add(DDBlocks.POLISHED_GLOOMSLATE_SLAB, "Polished Gloomslate Slab");
        translationBuilder.add(DDBlocks.POLISHED_GLOOMSLATE_WALL, "Polished Gloomslate Wall");
        translationBuilder.add(DDBlocks.GLOOMSLATE_BRICKS, "Gloomslate Bricks");
        translationBuilder.add(DDBlocks.GLOOMSLATE_BRICK_STAIRS, "Gloomslate Brick Stairs");
        translationBuilder.add(DDBlocks.GLOOMSLATE_BRICK_SLAB, "Gloomslate Brick Slab");
        translationBuilder.add(DDBlocks.GLOOMSLATE_BRICK_WALL, "Gloomslate Brick Wall");
        translationBuilder.add(DDBlocks.GLOOMSLATE_TILES, "Gloomslate Tiles");
        translationBuilder.add(DDBlocks.GLOOMSLATE_TILE_STAIRS, "Gloomslate Tile Stairs");
        translationBuilder.add(DDBlocks.GLOOMSLATE_TILE_SLAB, "Gloomslate Tile Slab");
        translationBuilder.add(DDBlocks.GLOOMSLATE_TILE_WALL, "Gloomslate Tile Wall");
        translationBuilder.add(DDBlocks.SMOOTH_GLOOMSLATE, "Smooth Gloomslate");
        translationBuilder.add(DDBlocks.SMOOTH_GLOOMSLATE_STAIRS, "Smooth Gloomslate Stairs");
        translationBuilder.add(DDBlocks.SMOOTH_GLOOMSLATE_SLAB, "Smooth Gloomslate Slab");
        translationBuilder.add(DDBlocks.SMOOTH_GLOOMSLATE_WALL, "Smooth Gloomslate Wall");
        translationBuilder.add(DDBlocks.CUT_GLOOMSLATE, "Cut Gloomslate");
        translationBuilder.add(DDBlocks.CUT_GLOOMSLATE_STAIRS, "Cut Gloomslate Stairs");
        translationBuilder.add(DDBlocks.CUT_GLOOMSLATE_SLAB, "Cut Gloomslate Slab");
        translationBuilder.add(DDBlocks.CUT_GLOOMSLATE_WALL, "Cut Gloomslate Wall");
        translationBuilder.add(DDBlocks.CHISELED_GLOOMSLATE, "Chiseled Gloomslate");
        translationBuilder.add(DDBlocks.GLOOMSLATE_BARRIER, "Gloomslate Barrier");
        translationBuilder.add(DDBlocks.FRAGILE_GLOOMSLATE_BRICKS, "Fragile Gloomslate Bricks");
        translationBuilder.add(DDBlocks.GLOOMSLATE_LOCK, "Gloomslate Lock");
        translationBuilder.add(DDBlocks.FORTIFIED_CUT_GLOOMSLATE, "Fortified Cut Gloomslate");
        translationBuilder.add(DDBlocks.ECHO_SOIL, "Echo Soil");
        translationBuilder.add(DDBlocks.ECHO_FARMLAND, "Echo Farmland");
        translationBuilder.add(DDBlocks.SCULK_GLEAM, "Sculk Gleam");
        translationBuilder.add(DDBlocks.SCULK_JAW, "Sculk Jaw");
        translationBuilder.add(DDBlocks.SCULK_STONE_COAL_ORE, "Sculk Stone Coal Ore");
        translationBuilder.add(DDBlocks.SCULK_STONE_IRON_ORE, "Sculk Stone Iron Ore");
        translationBuilder.add(DDBlocks.SCULK_STONE_COPPER_ORE, "Sculk Stone Copper Ore");
        translationBuilder.add(DDBlocks.SCULK_STONE_GOLD_ORE, "Sculk Stone Gold Ore");
        translationBuilder.add(DDBlocks.SCULK_STONE_REDSTONE_ORE, "Sculk Stone Redstone Ore");
        translationBuilder.add(DDBlocks.SCULK_STONE_EMERALD_ORE, "Sculk Stone Emerald Ore");
        translationBuilder.add(DDBlocks.SCULK_STONE_LAPIS_ORE, "Sculk Stone Lapis Lazuli Ore");
        translationBuilder.add(DDBlocks.SCULK_STONE_DIAMOND_ORE, "Sculk Stone Diamond Ore");
        translationBuilder.add(DDBlocks.GLOOMSLATE_COAL_ORE, "Gloomslate Coal Ore");
        translationBuilder.add(DDBlocks.GLOOMSLATE_IRON_ORE, "Gloomslate Iron Ore");
        translationBuilder.add(DDBlocks.GLOOMSLATE_COPPER_ORE, "Gloomslate Copper Ore");
        translationBuilder.add(DDBlocks.GLOOMSLATE_GOLD_ORE, "Gloomslate Gold Ore");
        translationBuilder.add(DDBlocks.GLOOMSLATE_REDSTONE_ORE, "Gloomslate Redstone Ore");
        translationBuilder.add(DDBlocks.GLOOMSLATE_EMERALD_ORE, "Gloomslate Emerald Ore");
        translationBuilder.add(DDBlocks.GLOOMSLATE_LAPIS_ORE, "Gloomslate Lapis Lazuli Ore");
        translationBuilder.add(DDBlocks.GLOOMSLATE_DIAMOND_ORE, "Gloomslate Diamond Ore");
        translationBuilder.add(DDBlocks.SCULK_TENDRILS_PLANT, "Sculk Tendrils Plant");
        translationBuilder.add(DDBlocks.SCULK_TENDRILS, "Sculk Tendrils");
        translationBuilder.add(DDBlocks.SCULK_VINES_PLANT, "Sculk Vines Plant");
        translationBuilder.add(DDBlocks.SCULK_VINES, "Sculk Vines");
        translationBuilder.add(DDBlocks.GLOWING_ROOTS_PLANT, "Glowing Roots Plant");
        translationBuilder.add(DDBlocks.GLOWING_ROOTS, "Glowing Roots");
        translationBuilder.add(DDBlocks.GLOWING_VINES_PLANT, "Glowing Vines Plant");
        translationBuilder.add(DDBlocks.GLOWING_VINES, "Glowing Vines");
        translationBuilder.add(DDBlocks.GLOOMY_CACTUS, "Gloomy Cactus");
        translationBuilder.add(DDBlocks.GLOOMY_GRASS, "Gloomy Grass");
        translationBuilder.add(DDBlocks.GLOOMY_SCULK, "Gloomy Sculk");
        translationBuilder.add(DDBlocks.GLOOMY_GEYSER, "Gloomy Geyser");
        translationBuilder.add(DDBlocks.POTTED_ECHO_SAPLING, "Potted Echo Sapling");
        translationBuilder.add(DDBlocks.POTTED_BLOOMING_STEM, "Potted Blooming Stem");
        translationBuilder.add(DDBlocks.POTTED_SCULK_SPRUCE_SAPLING, "Potted Sculk Spruce Sapling");
        translationBuilder.add(DDBlocks.ANCIENT_VASE, "Ancient Vase");
        translationBuilder.add(DDBlocks.CRYSTALLIZED_AMBER, "Crystallized Amber");
        translationBuilder.add(DDBlocks.INFESTED_SCULK, "Infested Sculk");
        translationBuilder.add(DDBlocks.SNOWY_SCULK_STONE, "Snowy Sculk Stone");
        translationBuilder.add(DDBlocks.SCULK_TUBERS, "Sculk Tubers");
        translationBuilder.add(DDBlocks.ICICLE, "Icicle");
        translationBuilder.add(DDBlocks.BLOOMING_SCULK_STONE, "Blooming Sculk Stone");
        translationBuilder.add(DDBlocks.BLOOMING_MOSS_BLOCK, "Blooming Moss Block");
        translationBuilder.add(DDBlocks.GLOWING_FLOWERS, "Glowing Flowers");
        translationBuilder.add(DDBlocks.GLOWING_GRASS, "Glowing Grass");
        translationBuilder.add(DDBlocks.BLOOMING_STEM, "Blooming Stem");
        translationBuilder.add(DDBlocks.STRIPPED_BLOOMING_STEM, "Stripped Blooming Stem");
        translationBuilder.add(DDBlocks.BLOOM_PLANKS, "Bloom Planks");
        translationBuilder.add(DDBlocks.BLOOM_STAIRS, "Bloom Stairs");
        translationBuilder.add(DDBlocks.BLOOM_SLAB, "Bloom Slab");
        translationBuilder.add(DDBlocks.BLOOM_FENCE, "Bloom Fence");
        translationBuilder.add(DDBlocks.BLOOM_FENCE_GATE, "Bloom Fence Gate");
        translationBuilder.add(DDBlocks.BLOOM_DOOR, "Bloom Door");
        translationBuilder.add(DDBlocks.BLOOM_TRAPDOOR, "Bloom Trapdoor");
        translationBuilder.add(DDBlocks.BLOOM_PRESSURE_PLATE, "Bloom Pressure Plate");
        translationBuilder.add(DDBlocks.BLOOM_BUTTON, "Bloom Button");
        translationBuilder.add(DDItems.BLOOM_BOAT, "Bloom Boat");
        translationBuilder.add(DDItems.BLOOM_CHEST_BOAT, "Bloom Boat with Chest");
        translationBuilder.add(DDBlocks.BLOOM_SIGN, "Bloom Sign");
        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.BLOCK.getKey(DDBlocks.BLOOM_WALL_SIGN)), "Bloom Wall Sign");
        translationBuilder.add(DDBlocks.BLOOM_HANGING_SIGN, "Bloom Hanging Sign");
        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.BLOCK.getKey(DDBlocks.BLOOM_WALL_HANGING_SIGN)), "Bloom Wall Hanging Sign");
        translationBuilder.add(DDBlocks.SOUNDPROOF_GLASS, "Soundproof Glass");
        translationBuilder.add(DDBlocks.PROTECTED_SCULK_GLEAM, "Protected Sculk Gleam");
        translationBuilder.add(DDBlocks.SCULK_LAMP, "Sculk Lamp");
        translationBuilder.add(DDBlocks.ICE_LILY, "Ice Lily");
        translationBuilder.add(Util.makeDescriptionId("tooltips", BuiltInRegistries.BLOCK.getKey(DDBlocks.ICE_LILY)) + ".flowerless", "Flowerless");
        translationBuilder.add(DDBlocks.LILY_FLOWER, "Lily Flower");
        translationBuilder.add(DDItems.LILY_FLOWER, "Lily Flower");
        translationBuilder.add(DDBlocks.SHATTERED_HEAD, "Shattered Head");
        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.BLOCK.getKey(DDBlocks.SHATTERED_WALL_HEAD)), "Shattered Wall Head");
        translationBuilder.add(DDBlocks.SCULK_TISSUE, "Sculk Tissue");
        translationBuilder.add(DDBlocks.DARK_FOUNTAIN, "Dark Fountain");
        translationBuilder.add(DDBlocks.SHADOW_CRYSTAL_BLOCK, "Block of Shadow Crystal");
        translationBuilder.add(DDBlocks.TOXIC_AIR, "Toxic Air");
        translationBuilder.add(DDBlocks.SCULK_FIRE, "Sculk Fire");
        translationBuilder.add(DDBlocks.SCULK_TORCH, "Sculk Torch");
        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.BLOCK.getKey(DDBlocks.SCULK_WALL_TORCH)), "Sculk Wall Torch");
        translationBuilder.add(DDBlocks.SCULK_CAMPFIRE, "Sculk Campfire");
        translationBuilder.add(DDBlocks.SCULK_LANTERN, "Sculk Lantern");
        translationBuilder.add(DDBlocks.PATIENCE_SOUL_FIRE, "Soul of Patience Fire");
        translationBuilder.add(DDBlocks.FORTITUDE_SOUL_FIRE, "Soul of Fortitude Fire");

        translationBuilder.add(DDItems.RESONARIUM, "Resonarium");
        translationBuilder.add(DDItems.RESONARIUM_HELMET, "Resonarium Helmet");
        translationBuilder.add(DDItems.RESONARIUM_CHESTPLATE, "Resonarium Chestplate");
        translationBuilder.add(DDItems.RESONARIUM_LEGGINGS, "Resonarium Leggings");
        translationBuilder.add(DDItems.RESONARIUM_BOOTS, "Resonarium Boots");
        translationBuilder.add(DDItems.RESONARIUM_SWORD, "Resonarium Sword");
        translationBuilder.add(DDItems.RESONARIUM_PICKAXE, "Resonarium Pickaxe");
        translationBuilder.add(DDItems.RESONARIUM_AXE, "Resonarium Axe");
        translationBuilder.add(DDItems.RESONARIUM_SHOVEL, "Resonarium Shovel");
        translationBuilder.add(DDItems.RESONARIUM_HOE, "Resonarium Hoe");
        translationBuilder.add(DDItems.WARDEN_HELMET, "Warden Helmet");
        translationBuilder.add(DDItems.WARDEN_CHESTPLATE, "Warden Chestplate");
        translationBuilder.add(DDItems.WARDEN_LEGGINGS, "Warden Leggings");
        translationBuilder.add(DDItems.WARDEN_BOOTS, "Warden Boots");
        translationBuilder.add(DDItems.WARDEN_SWORD, "Warden Sword");
        translationBuilder.add(DDItems.WARDEN_PICKAXE, "Warden Pickaxe");
        translationBuilder.add(DDItems.WARDEN_AXE, "Warden Axe");
        translationBuilder.add(DDItems.WARDEN_SHOVEL, "Warden Shovel");
        translationBuilder.add(DDItems.WARDEN_HOE, "Warden Hoe");
        translationBuilder.add("item." + DeeperDarker.MOD_ID + ".perks.immunity", "Immunity to:");
        translationBuilder.add("item." + DeeperDarker.MOD_ID + ".perks.dampens_vibrations", "Dampens Vibrations");
        translationBuilder.add(DDItems.REINFORCED_ECHO_SHARD, "Reinforced Echo Shard");
        translationBuilder.add(DDItems.WARDEN_CARAPACE, "Warden Carapace");
        translationBuilder.add(DDItems.HEART_OF_THE_DEEP, "Heart of the Deep");
        translationBuilder.add(DDItems.SOUL_CRYSTAL, "Soul Crystal");
        translationBuilder.add(DDItems.SOUL_DUST, "Soul Dust");
        translationBuilder.add(DDItems.SCULK_BONE, "Sculk Bone");
        translationBuilder.add(DDItems.SCULK_BONE_SHARD, "Sculk Bone Shard");
        translationBuilder.add(DDItems.OTHERSIDE_FIRE_STRIKER, "Otherside Fire Striker");
        translationBuilder.add(DDItems.PATIENCE_SOUL, "Soul of Patience");
        translationBuilder.add(DDItems.FORTITUDE_SOUL, "Soul of Fortitude");
        translationBuilder.add(DDItems.ROYAL_SCEPTER, "Royal Scepter");
        translationBuilder.add(DDItems.GRIME_BALL, "Grime Ball");
        translationBuilder.add(DDItems.GRIME_BRICK, "Grime Brick");
        translationBuilder.add(DDBlocks.SCULK_BASALT, "Sculk Basalt");
        translationBuilder.add(DDItems.ACID_BUCKET, "Acid Bucket");
        translationBuilder.add(DDItems.FIZZ, "Fizz");
        translationBuilder.add(DDItems.SCULK_DRINK, "Sculk Drink");
        translationBuilder.add(DDItems.ECHO_BOAT, "Echo Boat");
        translationBuilder.add(DDItems.ECHO_CHEST_BOAT, "Echo Boat with Chest");
        translationBuilder.add(DDItems.SCULK_SPRUCE_BOAT, "Sculk Spruce Boat");
        translationBuilder.add(DDItems.SCULK_SPRUCE_CHEST_BOAT, "Sculk Spruce Boat with Chest");
        translationBuilder.add(DDItems.SCULK_TRANSMITTER, "Sculk Transmitter");
        translationBuilder.add(DDItems.WHITE_SCULK_TRANSMITTER, "White Sculk Transmitter");
        translationBuilder.add(DDItems.ORANGE_SCULK_TRANSMITTER, "Orange Sculk Transmitter");
        translationBuilder.add(DDItems.MAGENTA_SCULK_TRANSMITTER, "Magenta Sculk Transmitter");
        translationBuilder.add(DDItems.LIGHT_BLUE_SCULK_TRANSMITTER, "Light Blue Sculk Transmitter");
        translationBuilder.add(DDItems.YELLOW_SCULK_TRANSMITTER, "Yellow Sculk Transmitter");
        translationBuilder.add(DDItems.LIME_SCULK_TRANSMITTER, "Lime Sculk Transmitter");
        translationBuilder.add(DDItems.PINK_SCULK_TRANSMITTER, "Pink Sculk Transmitter");
        translationBuilder.add(DDItems.GRAY_SCULK_TRANSMITTER, "Gray Sculk Transmitter");
        translationBuilder.add(DDItems.LIGHT_GRAY_SCULK_TRANSMITTER, "Light Gray Sculk Transmitter");
        translationBuilder.add(DDItems.CYAN_SCULK_TRANSMITTER, "Cyan Sculk Transmitter");
        translationBuilder.add(DDItems.PURPLE_SCULK_TRANSMITTER, "Purple Sculk Transmitter");
        translationBuilder.add(DDItems.BLUE_SCULK_TRANSMITTER, "Blue Sculk Transmitter");
        translationBuilder.add(DDItems.BROWN_SCULK_TRANSMITTER, "Brown Sculk Transmitter");
        translationBuilder.add(DDItems.GREEN_SCULK_TRANSMITTER, "Green Sculk Transmitter");
        translationBuilder.add(DDItems.RED_SCULK_TRANSMITTER, "Red Sculk Transmitter");
        translationBuilder.add(DDItems.BLACK_SCULK_TRANSMITTER, "Black Sculk Transmitter");
        translationBuilder.add(DDItems.SUPER_SCULK_TRANSMITTER, "Super Sculk Transmitter");
        translationBuilder.add(DDItems.ANGLER_FISH_SPAWN_EGG, "Angler Fish Spawn Egg");
        translationBuilder.add(DDItems.SCULK_SNAPPER_SPAWN_EGG, "Sculk Snapper Spawn Egg");
        translationBuilder.add(DDItems.SHATTERED_SPAWN_EGG, "Shattered Spawn Egg");
        translationBuilder.add(DDItems.SCULK_LEECH_SPAWN_EGG, "Sculk Leech Spawn Egg");
        translationBuilder.add(DDItems.SHRIEK_WORM_SPAWN_EGG, "Shriek Worm Spawn Egg");
        translationBuilder.add(DDItems.STALKER_SPAWN_EGG, "Stalker Spawn Egg");
        translationBuilder.add(DDItems.SLUDGE_SPAWN_EGG, "Sludge Spawn Egg");
        translationBuilder.add(DDItems.SCULK_CENTIPEDE_SPAWN_EGG, "Sculk Centipede Spawn Egg");
        translationBuilder.add(DDItems.POTTY_SPAWN_EGG, "Potty Spawn Egg");
        translationBuilder.add(DDItems.POT_SPAWN_EGG, "Pot Spawn Egg");
        translationBuilder.add(DDItems.POTTER_SPAWN_EGG, "Potter Spawn Egg");
        translationBuilder.add(DDItems.ACID_SPRITE_SPAWN_EGG, "Acid Sprite Spawn Egg");
        translationBuilder.add(DDItems.SOUL_ELYTRA, "Soul Elytra");
        translationBuilder.add(DDItems.SOUL_ELYTRA.getDescriptionId() + ".boost", "Press %s to Boost");
        translationBuilder.add(DDItems.SOUL_ELYTRA.getDescriptionId() + ".boost_disabled", "Boost disabled");
        translationBuilder.add(DDItems.SONOROUS_STAFF, "Sonorous Staff");
        translationBuilder.add(DDItems.BLOOM_BERRIES, "Bloom Berries");
        translationBuilder.add(DDItems.SCULK_TUBER, "Sculk Tuber");
        translationBuilder.add(DDItems.SCULK_BERRY_SPROUT, "Sculk Berry Sprout");
        translationBuilder.add(DDItems.SCULK_BERRY, "Sculk Berry");
        translationBuilder.add(DDItems.SHADOW_CRYSTAL, "Shadow Crystal");
        translationBuilder.add(DDItems.SUNGLASSES, "Sunglasses");
        translationBuilder.add(DDItems.RESONARIUM_PLATE, "Resonarium Plate");
        translationBuilder.add(DDItems.DAINTY_KEY, "Dainty Key");
        translationBuilder.add(DDItems.KEYBRAND, "Keybrand");

        translationBuilder.add(DeeperDarker.MOD_ID + ".key_type.too_large", "This key is too large...");
        translationBuilder.add(DeeperDarker.MOD_ID + ".key_type.too_small", "This key is too small...");

        translationBuilder.add(DDEnchantments.CATALYSIS, "Catalysis");
        translationBuilder.add(DDEnchantments.CATALYSIS.getDescriptionId() + ".desc", "Spreads sculk when mobs are killed.");
        translationBuilder.add(DDEnchantments.SCULK_SMITE, "Sculk Smite");
        translationBuilder.add(DDEnchantments.SCULK_SMITE.getDescriptionId() + ".desc", "Increases damage against sculk mobs such as Shattered and the Warden.");

        translationBuilder.add("block." + DeeperDarker.MOD_ID + ".linked", "Linked transmitter");
        translationBuilder.add("block." + DeeperDarker.MOD_ID + ".unlinked", "Unlinked transmitter");
        translationBuilder.add("block." + DeeperDarker.MOD_ID + ".not_transmittable", "Cannot link to block");
        translationBuilder.add("block." + DeeperDarker.MOD_ID + ".not_found", "The linked block is missing or unloaded");
        translationBuilder.add(DDItems.SCULK_TRANSMITTER.getDescriptionId() + ".unlink_confirm", "Press %s again to unlink");
        translationBuilder.add(DDItems.SCULK_TRANSMITTER.getDescriptionId() + ".link_confirm", "Press %s again to link");
        translationBuilder.add("tooltips." + DeeperDarker.MOD_ID + ".sculk_transmitter.linked", "Linked to %1$s");
        translationBuilder.add("tooltips." + DeeperDarker.MOD_ID + ".sculk_transmitter.location", "Located at %1$s, %2$s, %3$s");
        translationBuilder.add("tooltips." + DeeperDarker.MOD_ID + ".sculk_transmitter.location_advanced", "Dimension: %s");
        translationBuilder.add("tooltips." + DeeperDarker.MOD_ID + ".sculk_transmitter.not_linked", "Unlinked");

        translationBuilder.add(DDEntities.BOAT, "Boat");
        translationBuilder.add(DDEntities.CHEST_BOAT, "Boat with Chest");
        translationBuilder.add(DDEntities.ICICLE_SHARD, "Icicle Shard");
        translationBuilder.add(DDEntities.ANGLER_FISH, "Angler Fish");
        translationBuilder.add(DDEntities.SCULK_SNAPPER, "Sculk Snapper");
        translationBuilder.add(DDEntities.SHATTERED, "Shattered");
        translationBuilder.add(DDEntities.SCULK_LEECH, "Sculk Leech");
        translationBuilder.add(DDEntities.SHRIEK_WORM, "Shriek Worm");
        translationBuilder.add(DDEntities.STALKER, "Stalker");
        translationBuilder.add(DDEntities.SLUDGE, "Sludge");
        translationBuilder.add(DDEntities.SCULK_CENTIPEDE, "Sculk Centipede");
        translationBuilder.add(DDEntities.BLOOMING_GOLEM, "Blooming Golem");
        translationBuilder.add(DDEntities.POTTY, "Potty");
        translationBuilder.add(DDEntities.POT, "Pot");
        translationBuilder.add(DDEntities.POTTER, "Potter");
        translationBuilder.add(DDEntities.OVERCAST_VESSEL, "Overcast Vessel");
        translationBuilder.add(DDEntities.ACID_SPRITE, "Acid Sprite");

        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.MOB_EFFECT.getKey(DDEffects.SCULK_AFFINITY)), "Sculk Affinity");
        translationBuilder.add("item.minecraft.tipped_arrow.effect.sculk_affinity", "Arrow of Sculk Affinity");
        translationBuilder.add("item.minecraft.tipped_arrow.effect.long_sculk_affinity", "Arrow of Sculk Affinity");
        translationBuilder.add("item.minecraft.potion.effect.sculk_affinity", "Potion of Sculk Affinity");
        translationBuilder.add("item.minecraft.potion.effect.long_sculk_affinity", "Potion of Sculk Affinity");
        translationBuilder.add("item.minecraft.splash_potion.effect.sculk_affinity", "Splash Potion of Sculk Affinity");
        translationBuilder.add("item.minecraft.splash_potion.effect.long_sculk_affinity", "Splash Potion of Sculk Affinity");
        translationBuilder.add("item.minecraft.lingering_potion.effect.sculk_affinity", "Lingering Potion of Sculk Affinity");
        translationBuilder.add("item.minecraft.lingering_potion.effect.long_sculk_affinity", "Lingering Potion of Sculk Affinity");
        translationBuilder.add(Util.makeDescriptionId("block", BuiltInRegistries.MOB_EFFECT.getKey(DDEffects.HEMOPHILIA)), "Hemophilia");

        translationBuilder.add("subtitles.ambience.otherside_portal.groan", "The Otherside forebodes");
        translationBuilder.add("subtitles.entity.snapper.ambient", "Sculk Snapper breathes");
        translationBuilder.add("subtitles.entity.snapper.bite", "Sculk Snapper bites");
        translationBuilder.add("subtitles.entity.snapper.hurt", "Sculk Snapper hurts");
        translationBuilder.add("subtitles.entity.snapper.sniff", "Sculk Snapper sniffs");
        translationBuilder.add("subtitles.item.transmitter.error", "Transmitter fails");
        translationBuilder.add("subtitles.item.transmitter.link", "Transmitter links");
        translationBuilder.add("subtitles.item.transmitter.open", "Transmitter transmits");
        translationBuilder.add("subtitles.item.transmitter.unlink", "Transmitter unlinks");
        translationBuilder.add("subtitles.item.sonorous_staff.sonic_boom", "Sonorous Staff booms");
        translationBuilder.add("subtitles.ambient.otherside.additions", "Warden dreams");
        translationBuilder.add("subtitles.entity.shattered.ambient", "Shattered growls");
        translationBuilder.add("subtitles.entity.shattered.hurt", "Shattered hurts");
        translationBuilder.add("subtitles.entity.shattered.death", "Shattered dies");
        translationBuilder.add("subtitles.entity.shattered.notice", "Shattered takes notice");
        translationBuilder.add("subtitles.entity.leech.hurt", "Sculk Leech hurts");
        translationBuilder.add("subtitles.entity.shriek_worm.ambient", "Shriek Worm cries");
        translationBuilder.add("subtitles.entity.shriek_worm.hurt", "Shriek Worm hurts");
        translationBuilder.add("subtitles.entity.shriek_worm.death", "Shriek Worm dies");
        translationBuilder.add("subtitles.entity.stalker.ambient", "Stalker chirps");
        translationBuilder.add("subtitles.entity.stalker.hurt", "Stalker hurts");
        translationBuilder.add("subtitles.entity.stalker.death", "Stalker dies");
        translationBuilder.add("subtitles.entity.stalker.notice", "Stalker takes notice");
        translationBuilder.add("subtitles.entity.sludge.hurt", "Sludge hurts");
        translationBuilder.add("subtitles.entity.sludge.death", "Sludge dies");
        translationBuilder.add("subtitles.entity.sludge.squish", "Sludge squishes");
        translationBuilder.add("subtitles.entity.angler_fish.hurt", "Angler Fish hurts");
        translationBuilder.add("subtitles.entity.angler_fish.flop", "Angler Fish flops");
        translationBuilder.add("subtitles.entity.angler_fish.death", "Angler Fish dies");
        translationBuilder.add("subtitles.entity.icicle_shard.land", "Icicle shard lands");

        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".root.title", "Sculk Story");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".root.description", "You feel something pulling you toward the source...");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".find_ancient_city.title", "A Metropolis of Restless Souls");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".find_ancient_city.description", "Find an Ancient City");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".kill_warden.title", "Phantom Thief");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".kill_warden.description", "Slay the Warden and take its heart");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".enter_otherside.title", "Below the Bedrock");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".enter_otherside.description", "Deep below the bedrock, the darkness awaits");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".find_ancient_temple.title", "Abyssal Descent");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".find_ancient_temple.description", "Explore the depths for a temple");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".obtain_sculk_transmitter.title", "Remote Storage");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".obtain_sculk_transmitter.description", "Acquire a Sculk Transmitter");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".obtain_sonorous_staff.title", "Noise Complaint");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".obtain_sonorous_staff.description", "Acquire a Sonorous Staff");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".explore_otherside.title", "Echolocation");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".explore_otherside.description", "Explore all Otherside biomes");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".kill_all_otherside_mobs.title", "Sculk Slayer");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".kill_all_otherside_mobs.description", "Kill one of every Otherside hostile monster");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".obtain_reinforced_echo_shard.title", "Sculk Engineer");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".obtain_reinforced_echo_shard.description", "Reinforce an Echo Shard");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".warden_armor.title", "Cover Me with Sculk");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".warden_armor.description", "Protect yourself with a full set of Warden Armor");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".kill_all_pots.title", "Pot Luck");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".kill_all_pots.description", "Kill Potty, Pot, and Potter");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".kill_blooming_golem.title", "Patience is Key");
        translationBuilder.add("advancements." + DeeperDarker.MOD_ID + ".kill_blooming_golem.description", "Kill the Blooming Golem");

        translationBuilder.add("biome." + OthersideBiomes.DEEPLANDS.location().getNamespace() + "." + OthersideBiomes.DEEPLANDS.location().getPath(), "Deeplands");
        translationBuilder.add("biome." + OthersideBiomes.ECHOING_FOREST.location().getNamespace() + "." + OthersideBiomes.ECHOING_FOREST.location().getPath(), "Echoing Forest");
        translationBuilder.add("biome." + OthersideBiomes.OVERCAST_COLUMNS.location().getNamespace() + "." + OthersideBiomes.OVERCAST_COLUMNS.location().getPath(), "Overcast Columns");
        translationBuilder.add("biome." + OthersideBiomes.BLOOMING_CAVERNS.location().getNamespace() + "." + OthersideBiomes.BLOOMING_CAVERNS.location().getPath(), "Blooming Caverns");
        translationBuilder.add("biome." + OthersideBiomes.DARKLANDS.location().getNamespace() + "." + OthersideBiomes.DARKLANDS.location().getPath(), "Darklands");
        translationBuilder.add("biome." + OthersideBiomes.SCULK_SPRUCE_FOREST.location().getNamespace() + "." + OthersideBiomes.SCULK_SPRUCE_FOREST.location().getPath(), "Sculk Spruce Forest");
        translationBuilder.add("biome." + OthersideBiomes.ACID_FLOES.location().getNamespace() + "." + OthersideBiomes.ACID_FLOES.location().getPath(), "Acid Floes");

        translationBuilder.add("text.config.deeperdarker.title", "Deeper and Darker");
        translationBuilder.add("text.config.deeperdarker.category.server", "Server");
        translationBuilder.add("text.config.deeperdarker.category.client", "Client");
        translationBuilder.add("text.config.deeperdarker.option.client.wardenHeartPulses", "Heart of the Deep Pulses");
        translationBuilder.add("text.config.deeperdarker.option.client.wardenHeartPulses.tooltip", "Determines if the Heart of the Deep should\nemit a random pulsing sound.");
        translationBuilder.add("text.config.deeperdarker.option.client.renderWardenHelmetHorns", "Render Warden Helmet Horns");
        translationBuilder.add("text.config.deeperdarker.option.client.renderWardenHelmetHorns.tooltip", "Determines if the horns in the Warden\nHelmet should be rendered.");
        translationBuilder.add("text.config.deeperdarker.option.client.changePhantomTextures", "Change Phantom Textures");
        translationBuilder.add("text.config.deeperdarker.option.client.changePhantomTextures.tooltip", "Determines if Phantoms should have a\ndifferent texture in the Deeplands.");
        translationBuilder.add("text.config.deeperdarker.option.client.paintingFix", "Fix Ancient Paintings");
        translationBuilder.add("text.config.deeperdarker.option.client.paintingFix.tooltip", "Fixes desync that happens upon placing ancient\npaintings in places where they do not fit.");
        translationBuilder.add("text.config.deeperdarker.option.client.whiteFog", "White Fog");
        translationBuilder.add("text.config.deeperdarker.option.client.whiteFog.tooltip", "Changes the Otherside fog to be white instead of\nblack.");
        translationBuilder.add("text.config.deeperdarker.option.client.sculkTransmitterLinkCooldownSeconds", "Sculk Transmitter Cooldown");
        translationBuilder.add("text.config.deeperdarker.option.client.sculkTransmitterLinkCooldownSeconds.tooltip", "Measured in seconds. The cooldown to unlink or\nlink an already linked Sculk Transmitter.");
        translationBuilder.add("text.config.deeperdarker.option.server.spawnSomethingFromAncientVaseChance", "Ancient Vase Mob Spawn Chance");
        translationBuilder.add("text.config.deeperdarker.option.server.spawnSomethingFromAncientVaseChance.tooltip", "Defines the chance of a mob (Stalker or\nSculk Leech) spawning from an Ancient Vase.");
        translationBuilder.add("text.config.deeperdarker.option.server.sculkLeechesFromAncientVaseChance", "Sculk Leech Spawn Chance");
        translationBuilder.add("text.config.deeperdarker.option.server.sculkLeechesFromAncientVaseChance.tooltip", "Defines the chance of Sculk Leeches spawning\nfrom an Ancient Vase if the setting above ends up\nbeing true. If a mob should spawn and this\nsetting ends up being false, a Stalker will spawn.");
        translationBuilder.add("text.config.deeperdarker.option.server.geysersApplySlowFalling", "Geysers Apply Slow Falling");
        translationBuilder.add("text.config.deeperdarker.option.server.geysersApplySlowFalling.tooltip", "Determines if stepping on a Gloomy Geyser\ngrants the player Slow Falling.");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMinWidth", "Minimum Portal Width");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMinWidth.tooltip", "Defines the minimum width (not counting the\nframe) for an Otherside portal to be valid.");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMinHeight", "Minimum Portal Height");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMinHeight.tooltip", "Defines the minimum maxFloeHeight (not counting the\nframe) for an Otherside portal to be valid.");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMaxWidth", "Maximum Portal Width");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMaxWidth.tooltip", "Defines the maximum width (not counting the\nframe) for an Otherside portal to be valid.");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMaxHeight", "Maximum Portal Height");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMaxHeight.tooltip", "Defines the maximum maxFloeHeight (not counting the\nframe) for an Otherside portal to be valid.");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMinSearchHeight", "Minimum Portal Search Height");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMinSearchHeight.tooltip", "Defines the lowest Y coordinate to search to\ngenerate an Otherside portal. We recommend\nthat you set this to a value greater than or\nequal to 0 and less than the maximum portal\nsearch maxFloeHeight.");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMaxSearchHeight", "Maximum Portal Search Height");
        translationBuilder.add("text.config.deeperdarker.option.server.portalMaxSearchHeight.tooltip", "Defines the highest Y coordinate to search to\ngenerate an Otherside portal. We recommend\nthat you set this to a value greater than or\nequal to 0 and less than or equal to (126 - the\ngenerated portal's maxFloeHeight).");
        translationBuilder.add("text.config.deeperdarker.option.server.generatedPortalWidth", "Generated Portal Width");
        translationBuilder.add("text.config.deeperdarker.option.server.generatedPortalWidth.tooltip", "The width of Otherside portals generated when\ntraveling through dimensions and no portal is\navailable. Making this too large may cause problems.");
        translationBuilder.add("text.config.deeperdarker.option.server.generatedPortalHeight", "Generated Portal Height");
        translationBuilder.add("text.config.deeperdarker.option.server.generatedPortalHeight.tooltip", "The maxFloeHeight of Otherside portals generated when\ntraveling through dimensions and no portal is\navailable. Making this too large may cause problems.");
        translationBuilder.add("text.config.deeperdarker.option.server.geyserLaunchVelocity", "Gloomy Geyser Launch Velocity");
        translationBuilder.add("text.config.deeperdarker.option.server.geyserLaunchVelocity.tooltip", "Defines the velocity applied when a player is\nlaunched by a Gloomy Geyser.");
        translationBuilder.add("text.config.deeperdarker.option.server.sonorousStaffDamage", "Sonorous Staff Damage");
        translationBuilder.add("text.config.deeperdarker.option.server.sonorousStaffDamage.tooltip", "Determines the damage of the Sonorous Staff's sonic\nboom.");
        translationBuilder.add("text.config.deeperdarker.option.server.sonorousStaffKnockback", "Sonorous Staff Knockback");
        translationBuilder.add("text.config.deeperdarker.option.server.sonorousStaffKnockback.tooltip", "Determines the knockback of the Sonorous Staff's\nsonic boom applied to living entities.");
        translationBuilder.add("text.config.deeperdarker.option.server.sonorousStaffCooldown", "Sonorous Staff Cooldown");
        translationBuilder.add("text.config.deeperdarker.option.server.sonorousStaffCooldown.tooltip", "Determines the cooldown of the Sonorous Staff\nbefore the player can use it again.");
        translationBuilder.add("text.config.deeperdarker.option.server.sonorousStaffRange", "Sonorous Staff Range");
        translationBuilder.add("text.config.deeperdarker.option.server.sonorousStaffRange.tooltip", "Determines the range of the Sonorous Staff's sonic\nboom.");
        translationBuilder.add("text.config.deeperdarker.option.server.soulElytraCooldown", "Soul Elytra Cooldown");
        translationBuilder.add("text.config.deeperdarker.option.server.soulElytraCooldown.tooltip", "Determines the cooldown of the boost provided when\nboosting with Soul Elytra. Set to -1 to disable boost.");
        translationBuilder.add("text.config.deeperdarker.option.server.soulElytraBoostStrength", "Soul Elytra Boost Strength");
        translationBuilder.add("text.config.deeperdarker.option.server.soulElytraBoostStrength.tooltip", "Determines the strength of the boost provided\nwhen boosting with Soul Elytra.");
        translationBuilder.add("text.config.deeperdarker.option.server.snapperDropLimit", "Sculk Snapper Drop Limit");
        translationBuilder.add("text.config.deeperdarker.option.server.snapperDropLimit.tooltip", "Determines the maximum amount of books dropped\nby each Sculk Snapper. Set to -1 for infinite books.");

        translationBuilder.add("death.attack." + DeeperDarker.MOD_ID + ".bite", "%s was devoured");
        translationBuilder.add("death.attack." + DeeperDarker.MOD_ID + ".ring", "%s was given a deadly case of tinnitus by %s");
        translationBuilder.add("death.attack." + DeeperDarker.MOD_ID + ".dark_fountain", "%s was blinded by a dark fountain");
        translationBuilder.add("death.attack." + DeeperDarker.MOD_ID + ".icicle", "%s was skewered by a falling icicle");
        translationBuilder.add("death.attack." + DeeperDarker.MOD_ID + ".icicle.player", "%1$s was skewered by a falling icicle while fighting %2$s");
        translationBuilder.add("death.attack." + DeeperDarker.MOD_ID + ".acid", "%s tried to swim in acid");
        translationBuilder.add("death.attack." + DeeperDarker.MOD_ID + ".acid.player", "%1$s tried to swim in acid to escape %2$s");

        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".abstraction.title", "Abstraction");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".abstraction.author", "Pedro Ricardo");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".millipede.title", "Millipede");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".millipede.author", "Pedro Ricardo");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".clouds.title", "Clouds");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".clouds.author", "Pedro Ricardo");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".ooze.title", "Ooze");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".ooze.author", "Pedro Ricardo");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".adventure.title", "Adventure");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".adventure.author", "Pedro Ricardo");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".echoer.title", "Echoer");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".echoer.author", "Pedro Ricardo");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".carrot.title", "Back to Your Roots");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".carrot.author", "Pedro Ricardo");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".maze.title", "Maze");
        translationBuilder.add("painting." + DeeperDarker.MOD_ID + ".maze.author", "Pedro Ricardo");

        translationBuilder.add("key.categories." + DeeperDarker.MOD_ID, "Deeper and Darker");
        translationBuilder.add("key." + DeeperDarker.MOD_ID + ".boost", "Boost Soul Elytra");
        translationBuilder.add("key." + DeeperDarker.MOD_ID + ".transmit", "Use Sculk Transmitter");

        translationBuilder.add("tag.item." + DeeperDarker.MOD_ID + ".echo_logs", "Echo Logs");
        translationBuilder.add("tag.item." + DeeperDarker.MOD_ID + ".blooming_stems", "Blooming Stems");
        translationBuilder.add("tag.item." + DeeperDarker.MOD_ID + ".dampens_vibrations", "Dampens Vibrations");
        translationBuilder.add("tag.item." + DeeperDarker.MOD_ID + ".paintings", "Paintings");
        translationBuilder.add("tag.item." + DeeperDarker.MOD_ID + ".scutes", "Scutes");

        // Create
        translationBuilder.add(DDCreateCompat.Items.WARDEN_DIVING_HELMET.get(), "Warden Diving Helmet");
        translationBuilder.add(DDCreateCompat.Items.WARDEN_DIVING_BOOTS.get(), "Warden Diving Boots");
        translationBuilder.add(DDCreateCompat.Items.WARDEN_BACKTANK.get(), "Warden Backtank");
        translationBuilder.add(DDCreateCompat.Items.WARDEN_BACKTANK_PLACEABLE.get(), "Warden Backtank Placeable");

        translationBuilder.add("item.deeperdarker.warden_backtank.tooltip.behaviour1", "Provides _Pressurized_ _Air_ to Equipment that requires it.");
        translationBuilder.add("item.deeperdarker.warden_backtank.tooltip.behaviour2", "_Collects_ _Pressurized_ _Air_ at a rate depending on the Rotational Speed.");
        translationBuilder.add("item.deeperdarker.warden_backtank.tooltip.condition1", "When Worn");
        translationBuilder.add("item.deeperdarker.warden_backtank.tooltip.condition2", "When placed, Powered by Kinetics");
        translationBuilder.add("item.deeperdarker.warden_backtank.tooltip.summary", "A _Wearable_ _Tank_ for carrying Pressurized Air.");
        translationBuilder.add("item.deeperdarker.warden_diving_boots.tooltip.behaviour1", "Wielder _descends_ more _quickly_ in liquids. Grants the ability to _walk_ and _jump_ underwater. Wielder also is no longer affected by _Mechanical_ _Belts_.");
        translationBuilder.add("item.deeperdarker.warden_diving_boots.tooltip.condition1", "When Worn");
        translationBuilder.add("item.deeperdarker.warden_diving_boots.tooltip.summary", "A pair of _heavy_ _boots_, allowing for better traversal of the Ocean floor, including Oceans made of Lava.");
        translationBuilder.add("item.deeperdarker.warden_diving_helmet.tooltip.behaviour1", "Provides immunity to _Fire_ and _Lava_, slowly draining _Air Pressure_ from the Backtank. Also grants _improved vision_ in Lava");
        translationBuilder.add("item.deeperdarker.warden_diving_helmet.tooltip.condition1", "When Worn (Full set)");
        translationBuilder.add("item.deeperdarker.warden_diving_helmet.tooltip.summary", "Together with a _Netherite_ or _Warden Backtank_, this can protect you from _extreme heat_. To be effective, _Legs and Feet_ have to be covered in _Netherite_ or _Warden_.");

        translationBuilder.add("tooltips." + DeeperDarker.MOD_ID + ".reinvoked", "Reinvoked");
    }
}