package com.kyanite.deeperdarker;

import net.neoforged.neoforge.common.ModConfigSpec;
import org.apache.commons.lang3.tuple.Pair;

public class DeeperDarkerConfig {
    public static final DeeperDarkerConfig CONFIG;
    public static final ModConfigSpec CONFIG_SPEC;

    public final ModConfigSpec.DoubleValue fakeVaseChance;
    public final ModConfigSpec.DoubleValue stalkerSpawnChance;
    public final ModConfigSpec.IntValue soulElytraCooldown;
    public final ModConfigSpec.BooleanValue wardenHeartPulses;
    public final ModConfigSpec.IntValue snapperDropLimit;
    public final ModConfigSpec.IntValue othersidePortalWidth;
    public final ModConfigSpec.IntValue othersidePortalHeight;

    private DeeperDarkerConfig(ModConfigSpec.Builder builder) {
        fakeVaseChance = builder.comment("Chance of a vase being fake", "Default: 0.16").defineInRange("fakeVaseChance", 0.16, 0, 1);
        stalkerSpawnChance = builder.comment("Chance of a Stalker spawning when a fake vase is broken", "Default: 0.3125").defineInRange("stalkerSpawnChance", 0.3125, 0, 1);
        soulElytraCooldown = builder.comment("Soul Elytra's boost cooldown in ticks. Set to -1 to disable boost", "Default: 600").defineInRange("soulElytraCooldown", 600, -1, 12000);
        wardenHeartPulses = builder.comment("Heart of the Deep beats like a heart", "Default: true").define("wardenHeartPulses", true);
        snapperDropLimit = builder.comment("Limit the number of enchanted books a Sculk Snapper can drop", "Default: 8").defineInRange("snapperDropLimit", 8, 0, 32);
        othersidePortalWidth = builder.comment("Width of Otherside portal when generated by player", "Default: 6").defineInRange("othersidePortalWidth", 6, 2, 21);
        othersidePortalHeight = builder.comment("Height of Otherside portal when generated by player", "Default: 3").defineInRange("othersidePortalHeight", 3, 3, 21);
    }

    static {
        Pair<DeeperDarkerConfig, ModConfigSpec> pair = new ModConfigSpec.Builder().configure(DeeperDarkerConfig::new);
        CONFIG = pair.getLeft();
        CONFIG_SPEC = pair.getRight();
    }
}
